Tests for classes: EntryServiceImp, PersonServiceImp, Lecture, ScheduleDay
eiBoard-Company/Backend pull request #17
Opened 2023-05-16 12:15 UTC by juStadl

Bitte schaus dir an, wenn Fehler drin sind KYS weil das hat mich Nerven bis zum Umfallen gekostet c:

2023-05-16 21:54 UTC, Chemmic requested changes
Passt schon so größtenteils, les dir vielleicht alles erstmal durch bevor du änderungen vornimmst. Würde in unserem Fall fast nur die Services Testen, wir haben kaum Logik ansonsten.

2023-05-16 21:54 UTC, Chemmic commented on eiBoard/src/test/java/dhbw/eiCompany/service/EntryServiceImpTest.java
> +
Kannst so lassen, aber als allgemeiner Tipp, vielleicht eine extra Funktion schreiben wie z.B. private void assertEqualsEntry(Entry expected, Entry actual) {
   assertEquals(expected.getEntryId(), actual.getEntryId());
   etc.
}
und dann für entry1 bis 3 einfach die Methode aufrufen und entry übergeben

2023-05-16 21:54 UTC, Chemmic commented on eiBoard/src/test/java/dhbw/eiCompany/service/EntryServiceImpTest.java
> +
Angenommen man macht das richtig mockt man glaube ich alles. Also wenn service.findById aufgerufen wird, das ein gemocktes "Fake Objekt" zurück gegeben wird.
Also nur im allgemeinen, damit man in den Tests nicht mit den wirklichen Daten der Datenbank spielt. In der Praxis wäre das ja Problematisch wenn beim Kunden aufeinmal echte Daten bearbeitet werden.

Ich denke hier könntest du auch dein Entry1 oder so in der Datenbank speichern, das dann mit service.findById dir holen und die beiden Entrys dann vergleichen. (alternativ auch einfach ein Entry objekt anlegen welches die gleichen Inhalte hat wie das mit der ID 8, also auch id 8 etc. und dann schauen ob findById(8) das gleiche rausgibt, allerdings sollten die beispieldaten mal verschwinden würde der Test fehlschlagen..)

2023-05-16 21:54 UTC, Chemmic commented on eiBoard/src/test/java/dhbw/eiCompany/service/EntryServiceImpTest.java
> +
Denke kannst du lassen aber auch hier nur zur info für reale Projekte, wahrscheinlich das Ergebniss oder so irgendwie mocken. Weil sobald mehr Einträge drin sind schlägt der Test fehl. Also wahrscheinlich so was in der Art: https://www.baeldung.com/mockito-mock-methods (wie gesagt lass es ruhig so aber nur das du mal von gehört hast ;) )

2023-05-16 21:54 UTC, Chemmic commented on eiBoard/src/test/java/dhbw/eiCompany/service/PersonServiceImpTest.java
> +
Die Methode gibt auch ne Person zurück, lieber die Werte von Person3 und der zurückgegebenen Person vergleichen als die Listen Größe. Wie bei Entrys oben

2023-05-16 21:54 UTC, Chemmic commented on eiBoard/src/test/java/dhbw/eiCompany/service/PersonServiceImpTest.java
> +
Falls du für die Methode oben drüber eine seperate vergleichs Methode für Personen schreibst, könntest du diese mit searchedPerson und person1 aufrufen (siehe Kommentar zu Entrys) ansonsten lass es so.

2023-05-16 21:54 UTC, Chemmic commented on eiBoard/src/test/java/dhbw/eiCompany/service/PersonServiceImpTest.java
> +    @Test
Siehe Entry findById Kommentar

2023-05-16 21:54 UTC, Chemmic commented on eiBoard/src/test/java/dhbw/eiCompany/timetable/LectureTest.java
> +
Die ganzen Tests hier verstehe ich nicht ganz, wirken ziemlich überflüssig oder? Wenn du Lecture testen willst teste den LectureService, also die getDay und getWeek Methode.

2023-05-16 21:54 UTC, Chemmic commented on eiBoard/src/test/java/dhbw/eiCompany/timetable/ScheduleDayTest.java
> +@SpringBootTest
Will nicht nerven aber das hätte ich tendenziel auch weggelassen 🤒 Ist okay wenns über den LectureService getestet wird.

2023-05-17 07:12 UTC, juStadl commented on eiBoard/src/test/java/dhbw/eiCompany/service/EntryServiceImpTest.java
> +
done

2023-05-17 08:22 UTC, juStadl commented on eiBoard/src/test/java/dhbw/eiCompany/timetable/LectureTest.java
> +
Ich lass die unnötigen Tests stehen, schreibe aber auch noch tests für den service

2023-05-17 10:31 UTC, merged